import os


class PATH:
    BASE_DIR = "/Users/egorleontenkov/Desktop/Arcticle/REALISATION_PROJECT"
    DATA_DIR = "/Users/egorleontenkov/Desktop/Arcticle/IAM-OnDB/"
    MODEL_DIR = BASE_DIR + "/model/"
    SPLIT_CONFIG_DIR = DATA_DIR + "split-config/"
    LINE_DATA_DIR = DATA_DIR + "lineStrokes/"
    CHECKPOINTS_DIR = MODEL_DIR + "checkpoints/"


class PREPROCESS:
    SCHEME1 = {
        "slope_correction": True,
        "normalize": True,
        "down_cos": 0.975,
        "resample_distance": 0.37,
        "up_sample": 9,
    }
    CURRENT_SCHEME = SCHEME1


class DATA:

    BLACKLIST = [
        "h02-037-02",
        "a02-062-01",
        "a02-062-02",
        "a02-062-03",
        "e05-265z-04",
        "g04-060-02",
        "j06-278z-04",
        "h04-141z-03",
    ]

    CHARS_MLF = [
        "ex",
        "qu",
        "ga",
        "do",
        "am",
        "ti",
        "sl",
        "lb",
        "rb",
        "ls",
        "rs",
        "sr",
        "cm",
        "mi",
        "pl",
        "pt",
        "sp",
        "cl",
        "sc",
        "qm",
        "n0",
        "n1",
        "n2",
        "n3",
        "n4",
        "n5",
        "n6",
        "n7",
        "n8",
        "n9",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
    ]

    MLF_MAPPING = {
        "ex": "!",
        "qu": '"',
        "ga": "",
        "do": "",
        "am": "&",
        "ti": "'",
        "sl": "/",
        "lb": "(",
        "rb": ")",
        "ls": "[",
        "rs": "]",
        "sr": "*",
        "cm": ",",
        "mi": "-",
        "pl": "+",
        "pt": ".",
        "sp": " ",
        "cl": ":",
        "sc": ";",
        "qm": "?",
        "n0": "0",
        "n1": "1",
        "n2": "2",
        "n3": "3",
        "n4": "4",
        "n5": "5",
        "n6": "6",
        "n7": "7",
        "n8": "8",
        "n9": "9",
    }

    CHARS = [
        "!",
        '"',
        "",
        "",
        "&",
        "'",
        "/",
        "(",
        ")",
        "[",
        "]",
        "*",
        ",",
        "-",
        "+",
        ".",
        " ",
        ":",
        ";",
        "?",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "%",
    ]

    NON_ALPHAS = [
        "!",
        '"',
        "",
        "",
        "&",
        "'",
        "/",
        "(",
        ")",
        "[",
        "]",
        "*",
        ",",
        "-",
        "+",
        ".",
        " ",
        ":",
        ";",
        "?",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
    ]

    CHARS_SIZE = len(CHARS_MLF) + 1
    BLANK_IDX = len(CHARS_MLF)


class SPLIT:
    TRAIN = "trainset.txt"
    TEST = "testset_f.txt"
    VAL1 = "testset_v.txt"
    VAL2 = "testset_t.txt"
    TEST_EXAMPLE = "test_example.txt"
    ALL = "all"


LINE_BLACKLIST = []
